// #region Imports

import { ReactNode } from 'react'

import type { Metadata } from 'next'

import '@/app/globals.css'
import { inter } from '@/app/fonts'

// #endregion

interface RootLayoutProps {
  children: ReactNode
}

export const metadata: Metadata = {
  title: 'Proposals',
  // description: 'Generated by create next app',
}

/**
 * Root Layout of application.
 *
 * @layout
 * @see https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates#root-layout-required
 */
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt">
      <body className={(inter.className, 'antialiased')}>{children}</body>
    </html>
  )
}
